# Generated by Django 4.2.9 on 2026-03-31 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("academic", "Stress Académique"),
                            ("anxiety", "Anxiété"),
                            ("grief", "Deuil & Perte"),
                            ("relationship", "Relations"),
                            ("depression", "Dépression"),
                            ("trauma", "Trauma"),
                            ("other", "Autre"),
                        ],
                        default="academic",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyenne"),
                            ("high", "Élevée"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("in_progress", "En cours"),
                            ("resolved", "Résolu"),
                            ("closed", "Fermé"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("is_urgent", models.BooleanField(default=False)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("next_session_at", models.DateTimeField(blank=True, null=True)),
                ("session_location", models.CharField(blank=True, max_length=200)),
                (
                    "counselor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "counselor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier de soutien",
                "verbose_name_plural": "Dossiers de soutien",
                "db_table": "mm_support_cases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "is_private",
                    models.BooleanField(
                        default=False, help_text="Private notes not visible to students"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="cases.supportcase",
                    ),
                ),
            ],
            options={
                "db_table": "mm_case_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Changement de statut"),
                            ("counselor_assign", "Assignation conseiller"),
                            ("note_added", "Note ajoutée"),
                            ("session_scheduled", "Séance planifiée"),
                            ("message_sent", "Message envoyé"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("old_value", models.CharField(blank=True, max_length=100)),
                ("new_value", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="cases.supportcase",
                    ),
                ),
            ],
            options={
                "db_table": "mm_case_activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="supportcase",
            index=models.Index(
                fields=["student", "status"], name="mm_support__student_f73828_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportcase",
            index=models.Index(
                fields=["counselor", "status"], name="mm_support__counsel_543a61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportcase",
            index=models.Index(
                fields=["status", "priority"], name="mm_support__status_f61097_idx"
            ),
        ),
    ]
