import { createContext, useContext, useState, useEffect } from 'react'

const TRANSLATIONS = {
  en: {
    welcome: 'Welcome', signin_sub: 'Sign in to your mental health support portal',
    sign_in: 'Sign In', register: 'Register', role_as: 'Sign in as',
    student: 'Student', counselor: 'Counselor', admin: 'Administrator',
    email: 'Email Address', password: 'Password', signin_btn: 'Sign In',
    no_account: "Don't have an account?", register_here: 'Register here',
    first_name: 'First Name', last_name: 'Last Name', student_id: 'Student ID',
    create_account: 'Create Account', have_account: 'Already registered?',
    sign_in_here: 'Sign in',
    dashboard: 'Dashboard', my_cases: 'My Requests', cases: 'Cases',
    messages: 'Messages', resources: 'Resources', users: 'Users',
    reports: 'Reports', profile: 'Profile', settings: 'Settings',
    sign_out: 'Sign Out',
    hello: 'Hello',
    not_alone: 'You are not alone. Our counselors are here to support you every step of the way.',
    active_requests: 'Active Requests', unread_msgs: 'Unread Messages',
    resources_read: 'Resources Read', sessions_done: 'Sessions Done',
    new_request: '+ New Request', case_type: 'Type', priority: 'Priority',
    status: 'Status', submitted: 'Submitted',
    open: 'Open', in_progress: 'In Progress', resolved: 'Resolved', closed: 'Closed',
    low: 'Low', medium: 'Medium', high: 'High', urgent: 'Urgent',
    type_message: 'Type a message…', send: 'Send',
    save: 'Save', cancel: 'Cancel', submit: 'Submit',
    loading: 'Loading…', no_data: 'No data', search: 'Search…',
    safe_space: 'Your safe space', flag: '🇬🇧', lang_label: 'EN',
    tagline: 'Mental Health Support',
    quote: 'Every student deserves a safe space to grow, heal, and thrive.',
    edit_profile: 'Edit Profile', change_password: 'Change Password',
    preferences: 'Preferences', current_password: 'Current Password',
    new_password: 'New Password', confirm_password: 'Confirm Password',
    phone: 'Phone Number', bio: 'Bio', language: 'Interface Language',
    theme: 'Display Theme', dark_mode: 'Dark Mode', light_mode: 'Light Mode',
    active_case: 'Active Case', your_case: 'Your current support request',
    next_session: 'Next Session', scheduled: 'Scheduled appointment',
    quick_access: 'Quick Access', contact_counselor: 'Contact my counselor',
    explore_resources: 'Explore resources', my_requests: 'My requests',
    recommended: 'Recommended Resources', based_on: 'Based on your support profile',
    search_case: 'Search a case…', all_status: 'All Status', all_types: 'All Types',
    no_cases: 'No cases found', submit_request: 'Submit your first support request.',
    case_title: 'Title / Subject', describe: 'How are you feeling?',
    preferred_counselor: 'Preferred Counselor (optional)',
    no_preference: 'No preference', mark_urgent: 'Mark as urgent',
    urgent_help: 'If you need immediate help', submit_request_btn: 'Submit Request',
    new_conversation: '+ New Conversation', no_messages: 'No messages yet.',
    recipient: 'Recipient', choose_counselor: 'Choose a counselor…',
    initial_message: 'Initial message', start: 'Start',
    all: 'All', no_resources: 'No resources found', views: 'views', min_read: 'min read',
    open_cases: 'Open Cases', in_progress_cases: 'In Progress',
    resolved_cases: 'Resolved', urgent_cases: 'Urgent',
    by_type: 'Cases by Type', monthly_summary: 'Monthly Summary',
    resolution_rate: 'Resolution Rate', avg_response: 'Average Response Time',
    satisfaction: 'Student Satisfaction', export_pdf: 'Export PDF',
    all_users: 'All', students: 'Students', counselors: 'Counselors', admins: 'Admins',
    add_user: '+ Add User', full_name: 'Full Name', role: 'Role',
    joined: 'Joined', active: 'Active', inactive: 'Inactive',
    edit: 'Edit', deactivate: 'Deactivate', reactivate: 'Reactivate',
    no_active_cases: 'No active cases', submit_first: 'Submit a request to get started.',
    all_caught_up: 'All caught up!', no_open_cases: 'No open cases right now.',
    view_case: 'View case', confirm: 'Confirm', reschedule: 'Reschedule',
    add_note: 'Add a note', note_placeholder: 'Counseling notes, recommendations…',
    private_note: 'Private note (not visible to student)',
    case_history: 'Case History', case_info: 'Case Information',
    progress: 'Progress', assigned_to: 'Assigned to',
    session_location: 'Session location', update_case: 'Update Case',
    update_status: 'Update Status', assign_counselor: 'Assign Counselor',
    next_session_date: 'Next Session Date', session_place: 'Session Location',
    system_overview: 'System Overview', running_smoothly: 'MindMate is running smoothly.',
  },
  fr: {
    welcome: 'Bienvenue', signin_sub: 'Connectez-vous à votre portail de santé mentale',
    sign_in: 'Se Connecter', register: "S'inscrire", role_as: 'Se connecter en tant que',
    student: 'Étudiant', counselor: 'Conseiller', admin: 'Administrateur',
    email: 'Adresse Email', password: 'Mot de passe', signin_btn: 'Se connecter',
    no_account: 'Pas de compte ?', register_here: "S'inscrire ici",
    first_name: 'Prénom', last_name: 'Nom', student_id: 'Numéro étudiant',
    create_account: 'Créer un compte', have_account: 'Déjà inscrit ?',
    sign_in_here: 'Se connecter',
    dashboard: 'Tableau de bord', my_cases: 'Mes Demandes', cases: 'Dossiers',
    messages: 'Messages', resources: 'Ressources', users: 'Utilisateurs',
    reports: 'Rapports', profile: 'Profil', settings: 'Paramètres',
    sign_out: 'Déconnexion',
    hello: 'Bonjour',
    not_alone: "Vous n'êtes pas seul(e). Nos conseillers sont là pour vous soutenir.",
    active_requests: 'Demandes actives', unread_msgs: 'Messages non lus',
    resources_read: 'Ressources lues', sessions_done: 'Séances effectuées',
    new_request: '+ Nouvelle Demande', case_type: 'Type', priority: 'Priorité',
    status: 'Statut', submitted: 'Soumis le',
    open: 'Ouvert', in_progress: 'En cours', resolved: 'Résolu', closed: 'Fermé',
    low: 'Faible', medium: 'Moyenne', high: 'Élevée', urgent: 'Urgente',
    type_message: 'Écrire un message…', send: 'Envoyer',
    save: 'Enregistrer', cancel: 'Annuler', submit: 'Soumettre',
    loading: 'Chargement…', no_data: 'Aucune donnée', search: 'Rechercher…',
    safe_space: 'Votre espace sécurisé', flag: '🇫🇷', lang_label: 'FR',
    tagline: 'Soutien en Santé Mentale',
    quote: "Chaque étudiant mérite un espace sûr pour grandir et s'épanouir.",
    edit_profile: 'Modifier le profil', change_password: 'Changer le mot de passe',
    preferences: 'Préférences', current_password: 'Mot de passe actuel',
    new_password: 'Nouveau mot de passe', confirm_password: 'Confirmer le mot de passe',
    phone: 'Téléphone', bio: 'Bio', language: "Langue de l'interface",
    theme: "Thème d'affichage", dark_mode: 'Mode sombre', light_mode: 'Mode clair',
    active_case: 'Dossier Actif', your_case: 'Votre demande de soutien en cours',
    next_session: 'Prochaine Séance', scheduled: 'Rendez-vous planifié',
    quick_access: 'Accès Rapide', contact_counselor: 'Contacter mon conseiller',
    explore_resources: 'Explorer les ressources', my_requests: 'Mes demandes',
    recommended: 'Ressources Recommandées', based_on: 'Basées sur votre profil',
    search_case: 'Rechercher un dossier…', all_status: 'Tous les statuts',
    all_types: 'Tous les types', no_cases: 'Aucun dossier trouvé',
    submit_request: 'Soumettez votre première demande.',
    case_title: 'Titre / Sujet', describe: 'Comment vous sentez-vous ?',
    preferred_counselor: 'Conseiller préféré (optionnel)',
    no_preference: 'Pas de préférence', mark_urgent: 'Marquer comme urgent',
    urgent_help: "Si vous avez besoin d'aide immédiate",
    submit_request_btn: 'Soumettre la demande',
    new_conversation: '+ Nouvelle conversation', no_messages: 'Aucun message.',
    recipient: 'Destinataire', choose_counselor: 'Choisir un conseiller…',
    initial_message: 'Message initial', start: 'Démarrer',
    all: 'Tous', no_resources: 'Aucune ressource trouvée',
    views: 'lectures', min_read: 'min',
    open_cases: 'Dossiers ouverts', in_progress_cases: 'En cours',
    resolved_cases: 'Résolus', urgent_cases: 'Urgents',
    by_type: 'Dossiers par type', monthly_summary: 'Résumé mensuel',
    resolution_rate: 'Taux de résolution', avg_response: 'Temps de réponse moyen',
    satisfaction: 'Satisfaction étudiante', export_pdf: 'Exporter PDF',
    all_users: 'Tous', students: 'Étudiants', counselors: 'Conseillers', admins: 'Admins',
    add_user: '+ Ajouter', full_name: 'Nom complet', role: 'Rôle',
    joined: 'Inscrit le', active: 'Actif', inactive: 'Inactif',
    edit: 'Modifier', deactivate: 'Désactiver', reactivate: 'Réactiver',
    no_active_cases: 'Aucun dossier actif', submit_first: 'Soumettez une demande.',
    all_caught_up: 'Tout est traité !', no_open_cases: 'Aucun dossier ouvert.',
    view_case: 'Voir le dossier', confirm: 'Confirmer', reschedule: 'Reporter',
    add_note: 'Ajouter une note', note_placeholder: 'Notes de conseil…',
    private_note: 'Note privée (non visible par l\'étudiant)',
    case_history: 'Historique', case_info: 'Informations',
    progress: 'Progression', assigned_to: 'Assigné à',
    session_location: 'Lieu de la séance', update_case: 'Modifier le Dossier',
    update_status: 'Mettre à jour le statut', assign_counselor: 'Assigner un conseiller',
    next_session_date: 'Prochaine séance', session_place: 'Lieu',
    system_overview: "Vue d'ensemble", running_smoothly: 'MindMate fonctionne correctement.',
  },
  rw: {
    welcome: 'Murakaza Neza', signin_sub: "Injira kuri porotali y'ubuzima",
    sign_in: 'Injira', register: 'Iyandikishe', role_as: 'Injira nka',
    student: 'Umunyeshuri', counselor: 'Umujyanama', admin: 'Umuyobozi',
    email: 'Imeyili', password: "Ijambo ry'ibanga", signin_btn: 'Injira',
    no_account: 'Nta konti ufite?', register_here: 'Iyandikishe hano',
    first_name: "Izina ry'mbere", last_name: 'Irindi zina',
    student_id: "Numero y'umunyeshuri", create_account: 'Fungura konti',
    have_account: 'Usanzwe ufite konti?', sign_in_here: 'Injira',
    dashboard: 'Intangiriro', my_cases: 'Ibisabwa byanjye', cases: 'Ibibazo',
    messages: 'Ubutumwa', resources: 'Amakuru', users: 'Abakoresha',
    reports: 'Raporo', profile: 'Umwirondoro', settings: 'Igenamiterere',
    sign_out: 'Sohoka',
    hello: 'Mwaramutse',
    not_alone: 'Ntufite ikibazo. Abajyanama bacu bari hano kukufasha.',
    active_requests: 'Ibisabwa bikora', unread_msgs: 'Ubutumwa butasomwe',
    resources_read: 'Amakuru yasomwe', sessions_done: 'Inama zaranzwe',
    new_request: '+ Isaba Rishya', case_type: 'Ubwoko', priority: 'Uburemere',
    status: 'Imiterere', submitted: 'Byoherejwe',
    open: 'Bufunguye', in_progress: 'Birakora', resolved: 'Byakemutse', closed: 'Bifunze',
    low: 'Hasi', medium: 'Hagati', high: 'Hejuru', urgent: 'Byihutirwa',
    type_message: 'Andika ubutumwa…', send: 'Ohereza',
    save: 'Bika', cancel: 'Hagarika', submit: 'Ohereza',
    loading: 'Gutegereza…', no_data: 'Nta makuru', search: 'Shakisha…',
    safe_space: 'Ahantu hahifuje', flag: '🇷🇼', lang_label: 'RW',
    tagline: "Ubufasha bw'Ubuzima", quote: 'Buri munyeshuri akwiye kugira ahantu hahifuje.',
    edit_profile: 'Hindura umwirondoro', change_password: "Hindura ijambo ry'ibanga",
    preferences: 'Amahitamo', current_password: "Ijambo ry'ibanga rya none",
    new_password: "Ijambo ry'ibanga rishya", confirm_password: "Emeza ijambo",
    phone: 'Telefoni', bio: 'Ibisobanuro', language: "Ururimi", theme: 'Imiterere',
    dark_mode: "Uburyo bw'ijoro", light_mode: "Uburyo bw'umunsi",
    active_case: 'Ikibazo Gikora', your_case: 'Gusaba inkunga',
    next_session: 'Inama Ikurikira', scheduled: 'Inama yateganyijwe',
    quick_access: 'Kugera Vuba', contact_counselor: "Vugana n'umujyanama",
    explore_resources: 'Shakisha amakuru', my_requests: 'Ibisabwa byanjye',
    recommended: 'Amakuru Ateganijwe', based_on: 'Bishingiye ku makuru yawe',
    search_case: 'Shakisha ikibazo…', all_status: 'Imiterere yose',
    all_types: 'Ubwoko bwose', no_cases: 'Nta bibazo bibonetse',
    submit_request: 'Ohereza isaba rya mbere.',
    case_title: 'Umutwe', describe: 'Wumva ute?',
    preferred_counselor: 'Umujyanama ukunzwe',
    no_preference: 'Nta hitamo', mark_urgent: 'Shyira mu byihutirwa',
    urgent_help: 'Niba ukeneye ubufasha bwihutirwa',
    submit_request_btn: 'Ohereza isaba',
    new_conversation: '+ Ikiganiro Gishya', no_messages: 'Nta butumwa.',
    recipient: 'Uwakiriye', choose_counselor: 'Hitamo umujyanama…',
    initial_message: 'Ubutumwa bwa mbere', start: 'Tangira',
    all: 'Byose', no_resources: 'Nta makuru abonetse',
    views: 'abasomyi', min_read: 'iminota',
    open_cases: 'Bibazo bifunguye', in_progress_cases: 'Birakora',
    resolved_cases: 'Byakemutse', urgent_cases: 'Byihutirwa',
    by_type: 'Ibibazo mu bwoko', monthly_summary: "Incamake y'ukwezi",
    resolution_rate: "Igipimo cy'ibisubizo", avg_response: 'Igihe cyo gusubiza',
    satisfaction: "Ibyishimo by'abanyeshuri", export_pdf: 'Sohora PDF',
    all_users: 'Bose', students: 'Abanyeshuri', counselors: 'Abajyanama',
    admins: 'Abayobozi', add_user: '+ Ongeraho', full_name: 'Amazina yose',
    role: 'Uruhare', joined: 'Yinjiye ku', active: 'Akora', inactive: 'Ntakora',
    edit: 'Hindura', deactivate: 'Hagarika', reactivate: 'Ongera gutangira',
    no_active_cases: 'Nta bibazo bikora', submit_first: 'Ohereza isaba.',
    all_caught_up: 'Byose birakozwe!', no_open_cases: 'Nta bibazo bifunguye.',
    view_case: 'Reba ikibazo', confirm: 'Emeza', reschedule: 'Hindura igihe',
    add_note: 'Ongeraho icyitegererezo', note_placeholder: 'Ibitekerezo…',
    private_note: 'Icyitegererezo cyigenga',
    case_history: 'Amateka', case_info: 'Amakuru',
    progress: 'Iterambere', assigned_to: 'Wahawe',
    session_location: 'Aho inama izabera', update_case: 'Hindura Ikibazo',
    update_status: 'Hindura imiterere', assign_counselor: 'Ha umujyanama',
    next_session_date: 'Inama ikurikira', session_place: 'Aho bizabera',
    system_overview: "Incamake y'uburyo", running_smoothly: 'MindMate ikora neza.',
  },
}

const LANG_CYCLE = ['en', 'fr', 'rw']
const ThemeContext = createContext(null)

export function ThemeProvider({ children }) {
  const [theme, setTheme] = useState(() => localStorage.getItem('mm_theme') || 'light')
  const [lang, setLang]   = useState(() => localStorage.getItem('mm_lang')  || 'en')

  useEffect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark')
    localStorage.setItem('mm_theme', theme)
  }, [theme])

  useEffect(() => {
    localStorage.setItem('mm_lang', lang)
    document.documentElement.setAttribute('lang', lang)
  }, [lang])

  const toggleTheme = () => setTheme(t => t === 'light' ? 'dark' : 'light')

  const cycleLang = () => {
    setLang(l => {
      const idx = LANG_CYCLE.indexOf(l)
      return LANG_CYCLE[(idx + 1) % LANG_CYCLE.length]
    })
  }

  const t = key => TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS['en'][key] ?? key

  return (
    <ThemeContext.Provider value={{ theme, toggleTheme, lang, cycleLang, t }}>
      {children}
    </ThemeContext.Provider>
  )
}

export const useTheme = () => {
  const ctx = useContext(ThemeContext)
  if (!ctx) throw new Error('useTheme must be used inside ThemeProvider')
  return ctx
}
