# Generated by Django 4.2.9 on 2026-03-31 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("icon", models.CharField(default="📚", max_length=10)),
                ("color", models.CharField(default="#EBF3EC", max_length=20)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Resource categories",
                "db_table": "mm_resource_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                ("description", models.TextField()),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("video", "Vidéo"),
                            ("pdf", "PDF"),
                            ("guide", "Guide"),
                            ("audio", "Audio"),
                        ],
                        default="article",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Full article content or transcript"
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="resources/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="resource_thumbs/"
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("read_time_minutes", models.PositiveSmallIntegerField(default=5)),
                ("is_published", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="resources.resourcecategory",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mm_resources",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="resources.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mm_resource_views",
                "unique_together": {("resource", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["is_published", "category"],
                name="mm_resource_is_publ_541e48_idx",
            ),
        ),
    ]
